# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: User Center
  description: 用户中心API
  version: "1.0.0"
# the domain of the service
host: uc.local.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /signout:
    get:
      summary: 退出
      description: 用户退出此客户端.
      parameters:
        - name: hash
          in: query
          description: 登录验证后得到的hash, hash_app_key 数据库 key的格式
          required: true
          type: string
          format: string
        - name: time
          in: query
          description: 请求的时间戳, 用于生成 sign 签名
          required: true
          type: integer
          format: int32
        - name: sign
          in: query
          description: 签名
          required: true
          type: string
          format: string
        - name: app_key
          in: query
          description: 接口调用者的 APP_KEY
          required: true
          type: string
          format: string
      tags:
        - Signout
      responses:
        200:
          description: 服务器的响应, 成功会得到用户的资料
          schema:
            type: object
            items:
              $ref: '#/definitions/Response'


definitions:
  Data:
    type: object

  Response:
    type: object
    properties:
      data:
        type: object
        description: 响应的数据
        items:
          $ref: '#/definitions/Data'
      error:
        type: object
        items:
          $ref: '#/definitions/Error'

  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
