# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: User Center
  description: 用户中心API
  version: "1.0.0"
# the domain of the service
host: uc.local.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /signup:
    post:
      summary: 注册
      description: 用户注册接口. 支持手机, 邮箱.
      parameters:
        - name: account
          in: formData
          description: 登录账号, 手机号码或者邮箱地址
          required: true
          type: string
          format: string
        - name: passworld
          in: formData
          description: 登录密码
          required: true
          type: string
          format: string
        - name: passworld_confirmed
          in: formData
          description: 密码的再次输入的验证
          required: true
          type: string
          format: string
        - name: nickname
          in: formData
          description: 用户的昵称, 称呼吧.
          required: true
          type: string
          format: string
        - name: time
          in: formData
          description: 请求的时间戳, 用于生成 sign 签名
          required: true
          type: integer
          format: int32
        - name: sign
          in: formData
          description: 签名
          required: true
          type: string
          format: string
        - name: app_key
          in: formData
          description: 接口调用者的 APP_KEY
          required: true
          type: string
          format: string
      tags:
        - Signup
      responses:
        200:
          description: 登录成功后得到的 hash 值, 有时间限制.
          schema:
            type: object
            items:
              $ref: '#/definitions/Response'



definitions:
  Data:
    type: object
    properties:
      hash:
        type: string
        description: 登陆后的 hash 值

  Response:
    type: object
    properties:
      data:
        type: object
        description: 响应的数据
        items:
          $ref: '#/definitions/Data'
      error:
        type: object
        items:
          $ref: '#/definitions/Error'

  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
